version: '3.8'
services:
  db:
    image: postgres:13.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./dockerfiles/development/init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file: .env.development
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        environment: development
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env.development
    stdin_open: true
    tty: true
  test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        environment: test
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - test_gem_cache:/usr/local/bundle/gems
    env_file: .env.test
    stdin_open: true
    tty: true
volumes:
  gem_cache:
  test_gem_cache:
